services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  voicevox:
    image: voicevox/voicevox_engine:latest
    ports:
      - "50021:50021"
    deploy:
      resources: {}
